language: java

os:
  - linux

jdk:
  - oraclejdk8

branches:
  only:
    - master

install:
  - pip install --user -r requirements.txt
  - mvn clean install -Dmaven.javadoc.skip=true -B -V --settings settings.xml
