language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - pip install --upgrade pip enum34
  - pip install -r requirements.txt
  #- pip install matplotlib
  #- cd ~ && git clone https://github.com/nest/nest-simulator nest_source
  #- mkdir nest_install
  #- cd nest_source && mkdir build && cd build
  #- cmake -DCMAKE_INSTALL_PREFIX=~/nest_install .. && make && make install
  #- cd $TRAVIS_BUILD_DIR
  - pip install git+https://github.com/DimitriPlotnikov/ode-toolbox.git

install:
  - python setup.py install
  #- python PyNestML.py -path models -target target
  #- cd ../target && mkdir build && cd build
  #- cmake -Dwith-nest=~/nest_install/bin/nest-config .. && make && make install
  #- cd $TRAVIS_BUILD_DIR
  #- source $TRAVIS_BUILD_DIR/nest_install/bin/nest_vars.sh

sudo: true

script:
  - python tests/lexer_parser_test.py
  - python tests/special_block_parser_builder_test.py
  - python tests/expression_parser_test.py
  - python tests/ast_builder_test.py
  - python tests/symbol_table_builder_test.py
  - python tests/symbol_table_resolution_test.py
  - python tests/cocos_test.py
  - python tests/nest_codegenerator_test.py
  - python tests/pynestml_frontend_test.py
  - python tests/pynestml_frontend_test.py
  - python tests/nestml_test.py
  - python tests/expression_type_calculation_test.py
 # - python tests/resources/NestmlIntegrationTest.py

