language: java

os:
  - linux

jdk:
  - oraclejdk8

branches:
  only:
    - master

install:
  - pip install --user -r requirements.txt
  - mvn clean --settings settings.xml

script:
  - mvn install --settings settings.xml