language: java

os:
  - linux

jdk:
  - oraclejdk8

branches:
  only:
    - master

install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V --settings settings.xml

script: 
  - mvn surefire:test --settings settings.xml
