language: python

python:
  - "2.7"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"

before_install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - sudo python setup.py install

install:
  - pip install -r requirements.txt

sudo: true

script:
  - python pynestml/src/test/python/LexerParserTest.py
  - python pynestml/src/test/python/SpecialBlockParserBuilderTest.py
  - python pynestml/src/test/python/ExpressionParserTest.py
  - python pynestml/src/test/python/ASTBuilderTest.py
  - python pynestml/src/test/python/SymbolTableBuilderTest.py
  - python pynestml/src/test/python/SymbolTableResolutionTest.py
  - python pynestml/src/test/python/CoCosTest.py
  - python pynestml/src/test/python/PyNestMLFrontendTest.py
  - python pynestml/src/test/python/NESTMLTest.py