language: python

python:
  - "2.7"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"

before_install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - pip install --upgrade pip enum34
  - pip install -r requirements.txt
  - pip install matplotlib
  - git clone https://github.com/nest/nest-simulator nest_source
  - mkdir nest_install
  - cmake -DCMAKE_INSTALL_PREFIX=nest_install nest_source
  - make
  - make install

install:
  - python setup.py install
  - python PyNestML.py -path models -target target -dev
  - cd ../target
  - cmake -Dwith-nest=../nest_install/bin/nest-config .
  - make all
  - make install

sudo: true

script:
  - python tests/LexerParserTest.py
  - python tests/SpecialBlockParserBuilderTest.py
  - python tests/ExpressionParserTest.py
  - python tests/ASTBuilderTest.py
  - python tests/SymbolTableBuilderTest.py
  - python tests/SymbolTableResolutionTest.py
  - python tests/CoCosTest.py
  - python tests/PyNestMLFrontendTest.py
  - python tests/NESTMLTest.py
  - python tests/ExpressionTypeCalculationTest.py
  - python tests/resources/NestmlIntegrationTest.py

