language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt install openjdk-8-jre
  - wget http://www.antlr.org/download/antlr-4.7.1-complete.jar
  - echo \#\!/bin/bash > antlr4
  - echo java -cp \"`pwd`/antlr-4.7.1-complete.jar:$CLASSPATH\" org.antlr.v4.Tool \"\$@\" >> antlr4
  - echo >> antlr4
  - chmod +x antlr4
  - export PATH=$PATH:`pwd`
  - pip install --upgrade pip enum34
  - pip install -r requirements.txt
  #- pip install matplotlib
  #- cd ~ && git clone https://github.com/nest/nest-simulator nest_source
  #- mkdir nest_install
  #- cd nest_source && mkdir build && cd build
  #- cmake -DCMAKE_INSTALL_PREFIX=~/nest_install .. && make && make install
  #- cd $TRAVIS_BUILD_DIR
  - pip install git+https://github.com/DimitriPlotnikov/ode-toolbox.git

install:
  - find pynestml/generated -not -name __init__.py -a -not -name generated -delete
  - cd pynestml/grammars
  - ./generate_lexer_parser
  - cd ../..
  - export PYTHONPATH=$PYTHONPATH:`pwd`
  - echo $PYTHONPATH
  - python setup.py install
  #- python PyNestML.py -path models -target target
  #- cd ../target && mkdir build && cd build
  #- cmake -Dwith-nest=~/nest_install/bin/nest-config .. && make && make install
  #- cd $TRAVIS_BUILD_DIR
  #- source $TRAVIS_BUILD_DIR/nest_install/bin/nest_vars.sh

sudo: true

script:
  - echo $PYTHONPATH
  - python tests/lexer_parser_test.py
  - python tests/special_block_parser_builder_test.py
  - python tests/expression_parser_test.py
  - python tests/ast_builder_test.py
  - python tests/symbol_table_builder_test.py
  - python tests/symbol_table_resolution_test.py
  - python tests/cocos_test.py
  - python tests/nest_codegenerator_test.py
  - python tests/pynestml_frontend_test.py
  - python tests/nestml_test.py
  - python tests/expression_type_calculation_test.py
  - python tests/comment_test.py
  - python tests/as_component_test.py
  - python tests/magnitude_compatibility_test.py
  - python tests/nestml_printer_test.py
  - python tests/pynestml_2_nest_type_converter_test.py 
  - python tests/unit_system_test.py
# - python tests/resources/NestmlIntegrationTest.py

