language: java

os:
  - linux

jdk:
  - oraclejdk8


services:
  - docker
  
before_install:
  - docker build -t nestml .


install:
  - pip install --user -r requirements.txt
  - mvn clean

script:
  - mvn install
